//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsMobile.ServiceReferenceQuyen {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhanQuyen", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceMobile")]
    [System.SerializableAttribute()]
    public partial class PhanQuyen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaQuyenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenQuyenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaQuyen {
            get {
                return this.MaQuyenField;
            }
            set {
                if ((this.MaQuyenField.Equals(value) != true)) {
                    this.MaQuyenField = value;
                    this.RaisePropertyChanged("MaQuyen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenQuyen {
            get {
                return this.TenQuyenField;
            }
            set {
                if ((object.ReferenceEquals(this.TenQuyenField, value) != true)) {
                    this.TenQuyenField = value;
                    this.RaisePropertyChanged("TenQuyen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceQuyen.IServiceQuyen")]
    public interface IServiceQuyen {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuyen/findAll", ReplyAction="http://tempuri.org/IServiceQuyen/findAllResponse")]
        WindowsFormsMobile.ServiceReferenceQuyen.PhanQuyen[] findAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuyen/findAll", ReplyAction="http://tempuri.org/IServiceQuyen/findAllResponse")]
        System.Threading.Tasks.Task<WindowsFormsMobile.ServiceReferenceQuyen.PhanQuyen[]> findAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceQuyenChannel : WindowsFormsMobile.ServiceReferenceQuyen.IServiceQuyen, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceQuyenClient : System.ServiceModel.ClientBase<WindowsFormsMobile.ServiceReferenceQuyen.IServiceQuyen>, WindowsFormsMobile.ServiceReferenceQuyen.IServiceQuyen {
        
        public ServiceQuyenClient() {
        }
        
        public ServiceQuyenClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceQuyenClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceQuyenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceQuyenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsMobile.ServiceReferenceQuyen.PhanQuyen[] findAll() {
            return base.Channel.findAll();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsMobile.ServiceReferenceQuyen.PhanQuyen[]> findAllAsync() {
            return base.Channel.findAllAsync();
        }
    }
}
