//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsMobile.ServiceReferenceDanhMuc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DanhMucSP", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceMobile")]
    [System.SerializableAttribute()]
    public partial class DanhMucSP : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaDMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaDM {
            get {
                return this.MaDMField;
            }
            set {
                if ((object.ReferenceEquals(this.MaDMField, value) != true)) {
                    this.MaDMField = value;
                    this.RaisePropertyChanged("MaDM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenDM {
            get {
                return this.TenDMField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDMField, value) != true)) {
                    this.TenDMField = value;
                    this.RaisePropertyChanged("TenDM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDanhMuc.IServiceDanhMuc")]
    public interface IServiceDanhMuc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDanhMuc/findAll", ReplyAction="http://tempuri.org/IServiceDanhMuc/findAllResponse")]
        WindowsFormsMobile.ServiceReferenceDanhMuc.DanhMucSP[] findAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDanhMuc/findAll", ReplyAction="http://tempuri.org/IServiceDanhMuc/findAllResponse")]
        System.Threading.Tasks.Task<WindowsFormsMobile.ServiceReferenceDanhMuc.DanhMucSP[]> findAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDanhMuc/insert", ReplyAction="http://tempuri.org/IServiceDanhMuc/insertResponse")]
        bool insert(string madm, string tendm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDanhMuc/insert", ReplyAction="http://tempuri.org/IServiceDanhMuc/insertResponse")]
        System.Threading.Tasks.Task<bool> insertAsync(string madm, string tendm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDanhMuc/delete", ReplyAction="http://tempuri.org/IServiceDanhMuc/deleteResponse")]
        bool delete(string madm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDanhMuc/delete", ReplyAction="http://tempuri.org/IServiceDanhMuc/deleteResponse")]
        System.Threading.Tasks.Task<bool> deleteAsync(string madm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDanhMuc/update", ReplyAction="http://tempuri.org/IServiceDanhMuc/updateResponse")]
        bool update(string madm, string tendm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDanhMuc/update", ReplyAction="http://tempuri.org/IServiceDanhMuc/updateResponse")]
        System.Threading.Tasks.Task<bool> updateAsync(string madm, string tendm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDanhMuc/GetById", ReplyAction="http://tempuri.org/IServiceDanhMuc/GetByIdResponse")]
        WindowsFormsMobile.ServiceReferenceDanhMuc.DanhMucSP[] GetById(string madm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDanhMuc/GetById", ReplyAction="http://tempuri.org/IServiceDanhMuc/GetByIdResponse")]
        System.Threading.Tasks.Task<WindowsFormsMobile.ServiceReferenceDanhMuc.DanhMucSP[]> GetByIdAsync(string madm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDanhMuc/GetByName", ReplyAction="http://tempuri.org/IServiceDanhMuc/GetByNameResponse")]
        WindowsFormsMobile.ServiceReferenceDanhMuc.DanhMucSP[] GetByName(string tendm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDanhMuc/GetByName", ReplyAction="http://tempuri.org/IServiceDanhMuc/GetByNameResponse")]
        System.Threading.Tasks.Task<WindowsFormsMobile.ServiceReferenceDanhMuc.DanhMucSP[]> GetByNameAsync(string tendm);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDanhMucChannel : WindowsFormsMobile.ServiceReferenceDanhMuc.IServiceDanhMuc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDanhMucClient : System.ServiceModel.ClientBase<WindowsFormsMobile.ServiceReferenceDanhMuc.IServiceDanhMuc>, WindowsFormsMobile.ServiceReferenceDanhMuc.IServiceDanhMuc {
        
        public ServiceDanhMucClient() {
        }
        
        public ServiceDanhMucClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDanhMucClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDanhMucClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDanhMucClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsMobile.ServiceReferenceDanhMuc.DanhMucSP[] findAll() {
            return base.Channel.findAll();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsMobile.ServiceReferenceDanhMuc.DanhMucSP[]> findAllAsync() {
            return base.Channel.findAllAsync();
        }
        
        public bool insert(string madm, string tendm) {
            return base.Channel.insert(madm, tendm);
        }
        
        public System.Threading.Tasks.Task<bool> insertAsync(string madm, string tendm) {
            return base.Channel.insertAsync(madm, tendm);
        }
        
        public bool delete(string madm) {
            return base.Channel.delete(madm);
        }
        
        public System.Threading.Tasks.Task<bool> deleteAsync(string madm) {
            return base.Channel.deleteAsync(madm);
        }
        
        public bool update(string madm, string tendm) {
            return base.Channel.update(madm, tendm);
        }
        
        public System.Threading.Tasks.Task<bool> updateAsync(string madm, string tendm) {
            return base.Channel.updateAsync(madm, tendm);
        }
        
        public WindowsFormsMobile.ServiceReferenceDanhMuc.DanhMucSP[] GetById(string madm) {
            return base.Channel.GetById(madm);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsMobile.ServiceReferenceDanhMuc.DanhMucSP[]> GetByIdAsync(string madm) {
            return base.Channel.GetByIdAsync(madm);
        }
        
        public WindowsFormsMobile.ServiceReferenceDanhMuc.DanhMucSP[] GetByName(string tendm) {
            return base.Channel.GetByName(tendm);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsMobile.ServiceReferenceDanhMuc.DanhMucSP[]> GetByNameAsync(string tendm) {
            return base.Channel.GetByNameAsync(tendm);
        }
    }
}
